; ** siehe auch longpolling Konfiguration
[options]

addons_path = /mnt/enterprise-addons,/mnt/extra-addons
data_dir = /var/lib/odoo

; Master-DB Password
admin_passwd = G4J96Mhy4GuDrFTz57vC

; csv_internal_sep = ,
; db_maxconn = 64
; db_name = False
; db_template = template1
; dbfilter = .*
; debug_mode = False
; email_from = False
; list_db = True

; ** LOGGING
; log_db = False
; log_handler = [':INFO']
; log_level = info
; logfile = None

; longpolling_port = 8072
; max_cron_threads = 2
; osv_memory_age_limit = 1.0
; osv_memory_count_limit = False

; noch eine Einstellung fuer Werkzeug
proxy_mode = True

; Comma-separated list of server-wide modules, default=web
; (es tauchen immer wieder low-low-level Module auf, die das hier modifizieren)
; server_wide_modules = None

; smtp_password = False
; smtp_port = 25
; smtp_server = localhost
; smtp_ssl = False
; smtp_user = False
; xmlrpc = True
; xmlrpc_interface = 
; xmlrpc_port = 8069
; xmlrpcs = True
; xmlrpcs_interface = 
; xmlrpcs_port = 8071

; Use the unaccent function provided by the database when available
; unaccent = False


; *** TUNING
limit_memory_hard = 4096000000
limit_memory_soft = 3072000000
limit_request = 100000

; diese beiden schlagen sehr unangenehm zu bei Backup und Restore
; limit_time_cpu = 60
limit_time_cpu = 60000
; limit_time_real = 120
limit_time_real = 120000

; Number of requests a worker will process before being recycled and restarted.
; limit_request = 8196

; how many new process will be started to perform work
; 2024-10-23 mpo Testweises Setzen von workers und max_cron_threads
workers = 5
max_cron_threads = 2

